spring:
  application:
    name: api-gateway
  profiles:
    active: default
  config:
    import: optional:configserver:http://localhost:8888/
management:
  endpoints:
    web:
      exposure:
        include: "*"
