spring:
  application:
    name: config-service
  profiles:
    active: git
  cloud:
    config:
      server:
        git:
          uri: https://github.com/rnzmndz/config.git
          # optional
          default-label: main

server:
  port: 8888

logging:
  level:
    root: DEBUG